var a = new Humanizer.HumanizerNumberSpeller();
console.log(a.spell("25", "percent", false));
console.log(a.spell("25", "percents", false));
console.log(a.spell("3", "milks", false));
console.log(a.spell("3", "fox", false));
console.log(a.spell("2", "Cats's", false));
console.log(a.spell("2", "cat's", false));
console.log(a.spell("2", "cat'S", false));
console.log(a.spell("2", "cat'", false));
console.log(a.spell("2", "cat's", true));
console.log(a.spell("1", "Cats's", false));
console.log(a.spell("1", "cat's", false));
console.log(a.spell("1", "cat'S", false));
console.log(a.spell("1", "cat'", false));
console.log(a.spell("1", "cats'", true));
console.log(a.spell("2", "cat", true));
console.log(a.spell("2", "cat", false));
console.log(a.spell(-1, null, true));
console.log(a.spell(1, null, true));
console.log(a.spell("-0", null, false));
console.log(a.spell("0", null, false));
console.log(a.spell("-0", null, false, "de-DE"));
console.log(a.spell("0", null, false, "de-DE"));
console.log(a.spell("-0.9", null, false));
console.log(a.spell("-0.9", null, false, "de-DE"));
console.log(a.spell("-1040000560089.000102300", null, false));
console.log(a.spell(-1234566789.023, "cat", true));
console.log(a.spell(1234566000.203000, null, true));
console.log(a.spell(1234566030.023, null, true));
console.log(a.spell(0.0, null, false));
console.log(a.spell(0.0, null, true));
console.log(a.spell(0.000000000001, null, false));
console.log(a.spell(1, 'pens', false));
console.log(a.spell(2, 'pen', false));
console.log(a.spell("2", "Man", false));
console.log(a.spell("2", "editor-in-chief", false));
console.log(a.spell("1", "Passersby", false));
console.log(a.spell("1", "passerby", false));
console.log(a.spell("1500", "passerby", false));
console.log(a.spell("1500", "passersby", false));
console.log(a.spell("1234", null, false, "de-DE"));
console.log(a.spell("1234.05678", "cat", false, "de-DE"));
console.log(a.spell("12345678990.05678", "cat", false, "de-DE"));
console.log(a.spell("1234.05678", null, true, "de-DE"));

var b = new Humanizer.DateToOrdinalWordsExtensions();
console.log(b.toOrdinalWords(new Date()));
