export {default as humanize} from "./humanize";
export {default as dehumanize} from "./dehumanize";
export {default as transform} from "./transform";
export {default as IStringTransformer} from "./transform/IStringTransformer";
export {default as truncate} from "./truncate";
export {default as defaultVocabulary} from "./inflections/defaultVocabulary";
export {default as Vocabulary} from "./inflections/Vocabulary";
export * from "./transform";
export * from "./truncate";
export * from "./inflections";
